name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get commit tag
      id: commit
      uses: pr-mpt/actions-commit-hash@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/build.dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/launchpad:devel-${{ steps.commit.outputs.short }}
    - uses: addnab/docker-run-action@v3
      with:
        image: launchpad:devel-${{ steps.commit.outputs.short }}
        run: |
          /tmp/launchpad/oss_build.sh
          python3.8 -m launchpad.examples.hello_world.launch
          python3.8 -m launchpad.examples.consumer_producers.launch --lp_launch_type=local_mp
